### ISSUE TITLE
[feature]可否增加一个一言插件？

### ISSUE THREAD

**Issue by youlan2333** [Cp0204/CasaMOD#3]

**Comment by Cp0204** [comment]
先记下，你也可以PR。

以hello为例子，改几行代码就行了。

**Comment by Cp0204** [comment]
已增加

**Comment by youlan2333** [comment]
如果add-widget-quotable和add-widget-hello合二为一会不会更好:)
![image](https://github.com/Cp0204/CasaMOD/assets/64688148/28e0d19b-3f67-4f8f-a34f-44b45c4101fc)

**Comment by Cp0204** [comment]
> 如果add-widget-quotable和add-widget-hello合二为一会不会更好:) ![image](https://private-user-images.githubusercontent.com/64688148/326629326-28e0d19b-3f67-4f8f-a34f-44b45c4101fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDA3MjgsIm5iZiI6MTcxNDQ0MDQyOCwicGF0aCI6Ii82NDY4ODE0OC8zMjY2MjkzMjYtMjhlMGQxOWItM2Y2Ny00ZjhmLWEzNGYtNDRiNDVjNDEwMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNGNmNDU0YTI3NDBkNzZiZjIzY2I5ZjEyNmI0NTIwNmVmMWVkYjQyZmM3MWVlODQxNjRkN2M3OTk1YmRhODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W7rgWXX4XYOiXbg8gMpxCsmKedHgv718FsGTF4Gmj8I)

代码都在那里了，自己改

**Comment by ChishFoxcat** [comment]
> 如果add-widget-quotable和add-widget-hello合二为一会不会更好:) ![image](https://private-user-images.githubusercontent.com/64688148/326629326-28e0d19b-3f67-4f8f-a34f-44b45c4101fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE3NjksIm5iZiI6MTcxNzc0MTQ2OSwicGF0aCI6Ii82NDY4ODE0OC8zMjY2MjkzMjYtMjhlMGQxOWItM2Y2Ny00ZjhmLWEzNGYtNDRiNDVjNDEwMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzhhNDA2M2RiODI1MzJhNDIwMGE5MDZmOGNjZmU4MDM2N2EyNThlM2E1NzI2Y2MxYmJjYjk2ZjI5OTllZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHVKy8bIL9MRWcIgVKf769e0UZKjF71RJlQbPotOo7w)

我改好了
![image](https://github.com/Cp0204/CasaMOD/assets/76027184/51969b49-f171-4b43-b2f0-f6cf82343fba)

**Comment by Cp0204** [comment]
> > 如果add-widget-quotable和add-widget-hello合二为一会不会更好:) ![image](https://private-user-images.githubusercontent.com/64688148/326629326-28e0d19b-3f67-4f8f-a34f-44b45c4101fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE3NjksIm5iZiI6MTcxNzc0MTQ2OSwicGF0aCI6Ii82NDY4ODE0OC8zMjY2MjkzMjYtMjhlMGQxOWItM2Y2Ny00ZjhmLWEzNGYtNDRiNDVjNDEwMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzhhNDA2M2RiODI1MzJhNDIwMGE5MDZmOGNjZmU4MDM2N2EyNThlM2E1NzI2Y2MxYmJjYjk2ZjI5OTllZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHVKy8bIL9MRWcIgVKf769e0UZKjF71RJlQbPotOo7w)
> 
> 我改好了 ![image](https://private-user-images.githubusercontent.com/76027184/337551477-51969b49-f171-4b43-b2f0-f6cf82343fba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDI5MjYsIm5iZiI6MTcxNzc0MjYyNiwicGF0aCI6Ii83NjAyNzE4NC8zMzc1NTE0NzctNTE5NjliNDktZjE3MS00YjQzLWIyZjAtZjZjZjgyMzQzZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YmE5Y2MxZTY0YzU1OTNkY2U1MDM4MzczNWE2MjdhNDU3MTJiOTI3ODg0ZmIyMzBhYWQyMjE0YjgwMTg1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGLRw-DEW4Ljo9Xgl4BLogR2zTYpsSorKEShoJphjA8)

欢迎PR😏
