### ISSUE TITLE
Bing-wallpaper enhanchment? change blur and brightness

### ISSUE THREAD

**Issue by karilca** [Cp0204/CasaMOD#4]
Hello,
Is it possible maybe to have that bing wallpapers less blury? Can you add option to have. For me it does not look good. Thank you.

**Comment by Cp0204** [comment]
https://github.com/Cp0204/CasaMOD/blob/2ad5edd6acde3694a1dac6e8d4142c47a2cbdeca/app/mod/bing-wallpaper-v2/mod.js#L25

You can find the mod.js file and edit this line:

```js
bgElement.style.filter = 'blur(0px) brightness(1)'; 
```

blur(0px) ---  Don't blur
brightness(1) --- Don't darken (Brightness 100%)

**Comment by karilca** [comment]
Thank you,
Now fixed
