### ISSUE TITLE
hide-some-app 该如何去隐藏其他的应用

### ISSUE THREAD

**Issue by ChishFoxcat** [Cp0204/CasaMOD#5]
如题

尝试应用的标题，并未成功

**Comment by Cp0204** [comment]
用应用的id，应用设置 - 导出compose 中可查看，例如
```
name:emby
...
```
emby就是

**Comment by ChishFoxcat** [comment]
> 用应用的id，应用设置 - 导出compose 中可查看，例如
> 
> ```
> name:emby
> ...
> ```
> 
> emby就是

```
#app-{name} {
  display: none;
}
```
> `{name}` 应用id

这么写吗？

还是说就写 `#app-{name}` 就行了

**Comment by Cp0204** [comment]
前者，我看你的项目，你不是也会前端嘛😂

这玩意儿没那么复杂，就是个挂个css隐藏元素，DOM id选择器。你F12看一下就知道了

**Comment by ChishFoxcat** [comment]
> 前者，我看你的项目，你不是也会前端嘛😂
> 
> 这玩意儿没那么复杂，就是个挂个css隐藏元素，DOM id选择器。你F12看一下就知道了

谢谢你的回复

没有清楚这个原理，只是想多问几下，抱歉抱歉
~~前端不咋会，都是一点一点搜出来~~

**Comment by Cp0204** [comment]
> > 前者，我看你的项目，你不是也会前端嘛😂
> > 这玩意儿没那么复杂，就是个挂个css隐藏元素，DOM id选择器。你F12看一下就知道了
> 
> 谢谢你的回复
> 
> 没有清楚这个原理，只是想多问几下，抱歉抱歉 ~前端不咋会，都是一点一点搜出来~

没事没事，这应用mod的原理都是通过挂一个js或css来达到修改casaos页面的目的。 只要选择器写得好，同理可以隐藏页面上任何元素。

**Comment by ChishFoxcat** [comment]
> > > 前者，我看你的项目，你不是也会前端嘛😂
> > > 这玩意儿没那么复杂，就是个挂个css隐藏元素，DOM id选择器。你F12看一下就知道了
> > 
> > 
> > 谢谢你的回复
> > 没有清楚这个原理，只是想多问几下，抱歉抱歉 ~前端不咋会，都是一点一点搜出来~
> 
> 没事没事，这应用mod的原理都是通过挂一个js或css来达到修改casaos页面的目的。 只要选择器写得好，同理可以隐藏页面上任何元素。

明白了，谢谢你
